import { afterEach, describe, expect, it, vi } from 'vitest'

afterEach(() => {
  vi.resetModules()
  vi.restoreAllMocks()
  document.body.replaceChildren()
})

async function setupRuntime() {
  let receive: ((request: { requestId: string; code: string; previewSeconds: number }) => void) | undefined
  const complete = vi.fn()
  const fail = vi.fn()
  window.strudelHost = {
    onRender(callback) { receive = callback; return () => { receive = undefined } },
    complete,
    fail,
  }
  const evaluate = vi.fn(async () => ({ queryArc: () => [] }))
  const clear = vi.fn()
  class TestEditor extends HTMLElement {
    code = ''
    editor = {
      prebaked: Promise.resolve(),
      repl: { evaluate, scheduler: { cps: 0.5 } },
      clear,
    }
  }
  if (!customElements.get('test-strudel-editor')) customElements.define('test-strudel-editor', TestEditor)
  const createElement = document.createElement.bind(document) as (name: string) => HTMLElement
  vi.spyOn(document, 'createElement').mockImplementation(((name: string) => (
    name === 'strudel-editor' ? new TestEditor() : createElement(name)
  )) as typeof document.createElement)
  const createObjectURL = vi.fn(() => 'blob:preview')
  Object.defineProperty(URL, 'createObjectURL', { value: createObjectURL, configurable: true })
  Object.defineProperty(URL, 'revokeObjectURL', { value: vi.fn(), configurable: true })
  vi.doMock('@strudel/repl', () => ({}))
  vi.doMock('@strudel/webaudio', () => ({
    renderPatternAudio: vi.fn(async () => {
      const bytes = new Uint8Array(44)
      new TextEncoder().encodeInto('RIFF', bytes.subarray(0, 4))
      new TextEncoder().encodeInto('WAVE', bytes.subarray(8, 12))
      URL.createObjectURL(new Blob([bytes], { type: 'audio/wav' }))
    }),
  }))
  await import('./strudelRuntime')
  return { receive: () => receive, complete, fail, evaluate, clear }
}

describe('isolated Strudel renderer', () => {
  it('evaluates a bounded request and returns generated bytes', async () => {
    const runtime = await setupRuntime()
    runtime.receive()?.({ requestId: 'a'.repeat(32), code: 'note("c3")', previewSeconds: 2 })
    await vi.waitFor(() => expect(runtime.complete).toHaveBeenCalledOnce())
    expect(runtime.complete.mock.calls[0][0]).toBe('a'.repeat(32))
    expect(runtime.complete.mock.calls[0][1]).toBeInstanceOf(ArrayBuffer)
    expect(runtime.evaluate).toHaveBeenCalledWith('note("c3")', false, true)
    expect(runtime.clear).toHaveBeenCalledOnce()
    expect(runtime.fail).not.toHaveBeenCalled()
  })

  it('rejects invalid requests without evaluating them', async () => {
    const runtime = await setupRuntime()
    runtime.receive()?.({ requestId: 'bad', code: 'note("c3")', previewSeconds: 2 })
    await vi.waitFor(() => expect(runtime.fail).toHaveBeenCalledWith('bad', 'Pattern render request is invalid'))
    expect(runtime.evaluate).not.toHaveBeenCalled()
    expect(runtime.complete).not.toHaveBeenCalled()
  })
})
